from __future__ import annotations

from code2paper.agentic.contracts import EvidencePolicy, StageToolSpec


def canonical_stage_tool_specs() -> list[StageToolSpec]:
    return [
        StageToolSpec(
            name="code2paper_input_resolution",
            stage="input_resolution",
            description="Resolve author intent into strict AuthorMarkers before code grounding.",
            output_artifacts=["resolved_author_markers", "input_manifest"],
            evidence_policy=EvidencePolicy.NONE,
            allow_model_decision=True,
        ),
        StageToolSpec(
            name="code2paper_intake",
            stage="intake",
            description="Retrieve implementation evidence from the target repository.",
            input_artifacts=["resolved_author_markers"],
            output_artifacts=[
                "retrieval_plan",
                "rescan_focus",
                "symbol_index",
                "retrieval_coverage",
                "retrieval_decision_context",
                "retrieval_rescan_plan",
                "retrieval_rescan_report",
                "retrieval_summary",
                "retrieval_strategy_manifest",
                "evidence_raw",
                "sources",
                "snippets",
                "intake_alignment",
                "intake_manifest",
            ],
            evidence_policy=EvidencePolicy.RETRIEVES_EVIDENCE,
            allow_model_decision=True,
        ),
        StageToolSpec(
            name="code2paper_analysis",
            stage="analysis",
            description="Analyze snippets into code facts, graph, entity links, and code-method alignment.",
            input_artifacts=["evidence_raw", "sources", "snippets", "intake_alignment"],
            output_artifacts=[
                "alignment",
                "analysis",
                "facts",
                "code_graph",
                "entity_map",
                "analysis_repair_focus",
                "analysis_repair_tasks",
                "analysis_manifest",
            ],
            evidence_policy=EvidencePolicy.ANALYZES_EVIDENCE,
            allow_model_decision=True,
        ),
        StageToolSpec(
            name="code2paper_evidence_freeze",
            stage="evidence",
            description="Freeze verified implementation evidence into writing-ready MethodEvidence and claim maps.",
            input_artifacts=["evidence_raw", "alignment", "analysis"],
            output_artifacts=["evidence", "claims", "claim_verification", "evidence_notes", "evidence_manifest"],
            required_output_artifacts=["evidence", "claims", "claim_verification"],
            evidence_policy=EvidencePolicy.FREEZES_EVIDENCE,
            hard_gate=True,
        ),
        StageToolSpec(
            name="code2paper_grounding",
            stage="grounding",
            description="Ground equations, symbols, and authoring context from frozen evidence.",
            input_artifacts=["evidence", "claims"],
            output_artifacts=["grounding_context", "equations_tex", "symbols_tex", "grounding_manifest"],
            evidence_policy=EvidencePolicy.CONSUMES_FROZEN_EVIDENCE,
        ),
        StageToolSpec(
            name="code2paper_authoring",
            stage="authoring",
            description="Write Method prose guided by author intent and constrained by frozen code evidence.",
            input_artifacts=[
                "evidence",
                "claims",
                "claim_verification",
                "evidence_sufficiency_report",
                "evidence_sufficiency_decision_trace",
                "grounding_context",
            ],
            output_artifacts=[
                "authoring_constraints",
                "authoring_context",
                "authoring_plan",
                "authoring_plan_decision_trace",
                "text_md",
                "text_tex",
                "text_claims",
                "authoring_manifest",
            ],
            required_output_artifacts=[
                "authoring_constraints",
                "authoring_context",
                "authoring_plan",
                "authoring_plan_decision_trace",
                "text_md",
            ],
            evidence_policy=EvidencePolicy.CONSUMES_FROZEN_EVIDENCE,
            allow_model_decision=True,
            hard_gate=True,
        ),
        StageToolSpec(
            name="code2paper_validation",
            stage="validation",
            description="Validate claim evidence, numeric facts, equations, terminology, LaTeX, and fidelity.",
            input_artifacts=["text_md", "evidence", "claims"],
            output_artifacts=["fidelity", "qa_claims", "qa_numbers", "qa_equations", "qa_terms", "qa_latex", "validation_manifest"],
            required_output_artifacts=["fidelity", "validation_manifest"],
            evidence_policy=EvidencePolicy.VALIDATES_EVIDENCE,
            hard_gate=True,
        ),
        StageToolSpec(
            name="code2paper_rendering",
            stage="rendering",
            description="Render method PDF and method overview figure from validated evidence-backed method content.",
            input_artifacts=[
                "text_tex",
                "evidence",
                "claims",
                "claim_verification",
                "validation_manifest",
                "agentic_invariant_audit",
                "traceability_ledger",
            ],
            output_artifacts=[
                "figure_plan",
                "figure_plan_decision_trace",
                "method_overview_meta",
                "method_overview_png",
                "text_pdf",
                "rendering_manifest",
            ],
            required_output_artifacts=["figure_plan", "figure_plan_decision_trace", "rendering_manifest"],
            evidence_policy=EvidencePolicy.CONSUMES_FROZEN_EVIDENCE,
            allow_model_decision=True,
            hard_gate=True,
        ),
        StageToolSpec(
            name="code2paper_finalize",
            stage="finalize",
            description="Assemble final Method package and run manifest.",
            input_artifacts=["text_tex", "rendering_manifest", "agentic_invariant_audit", "traceability_ledger"],
            output_artifacts=["final_tex", "final_pdf", "finalize_manifest"],
            required_output_artifacts=["final_tex", "finalize_manifest"],
            evidence_policy=EvidencePolicy.CONSUMES_FROZEN_EVIDENCE,
            hard_gate=True,
        ),
    ]
