"""Prompt template identifiers and versions."""

PROMPT_TEMPLATE_VERSION = "phase1_4_redesign_v1"

NAVIGATION_PLANNER_PROMPT_ID = "navigation_planner"
TARGETED_TRACER_PROMPT_ID = "targeted_tracer"
CODE_METHOD_ALIGNER_PROMPT_ID = "code_method_aligner"
STAGE_BUILDER_PROMPT_ID = "stage_builder"
MECHANISM_BUILDER_PROMPT_ID = "mechanism_builder"
DISTINGUISHING_MECHANISM_BUILDER_PROMPT_ID = "distinguishing_mechanism_builder"
AUTHOR_LOGIC_MAPPER_PROMPT_ID = "author_logic_mapper"
CLAIM_CONTRACT_BUILDER_PROMPT_ID = "claim_contract_builder"
NEGATIVE_SCOPE_BUILDER_PROMPT_ID = "negative_scope_builder"
METHOD_OUTLINE_PROMPT_ID = "method_outline_planner"
TERMINOLOGY_TABLE_PROMPT_ID = "terminology_table_builder"
DRAFT_MARKDOWN_PROMPT_ID = "draft_markdown_writer"
DRAFT_LATEX_PROMPT_ID = "draft_latex_writer"
DRAFT_CLAIM_MAPPER_PROMPT_ID = "draft_claim_mapper"
SELF_CRITIC_PROMPT_ID = "self_critic"
TARGETED_REVISER_PROMPT_ID = "targeted_reviser"
